### ISSUE TITLE
Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by ryanbuening** [ctrl-alt-d/blazor-dom-confetti#11]
I'm receiving the following error when deploying my Blazor Server app to my IIS site:

![image](https://user-images.githubusercontent.com/812974/111716301-1b20b900-882c-11eb-994a-9c96edc0e3bc.png)

**Comment by ctrl-alt-d** [comment]
Hi @ryanbuening !

Sorry about delay answering. Did you fix the issue in your side?

If not, qre you hosting the app at a sub-URL? If it's your case, please, try using this in `_Host.cshtml` File:

```html
<base rel='nofollow' href="/myblazorapp/" />
```

And this in `Startup.cs` File:

```c#
app.UsePathBase("/myblazorapp");
```

Source: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-5.0&tabs=visual-studio#app-base-path

Also, notice I just update node modules to last version.

Regards.

**Comment by ryanbuening** [comment]
Hey, I'm not using the package at the moment, but my guess is that was the reason. I **was** hosting the app at a sub-URL. Thanks for the info!
